# Generated by Django 2.1.4 on 2019-03-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cnic', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=32)),
                ('confirm_password', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=100)),
                ('experience', models.TextField()),
                ('min_charges', models.IntegerField()),
                ('max_charges', models.IntegerField()),
                ('other_detail', models.TextField()),
            ],
        ),
    ]
